
import { Container } from '@/Componentes/Container'
import { GrupAudios } from '@/Componentes/GrupAudios'
import Head from 'next/head'


export default function Home() {
  
  return (
    <>
      <Head>
        <title>Sound Board Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
     <GrupAudios
     />

      </Container>
     
      
    </>
  )
}
